# This file defines the data model required by the Twilio extension.
namespace: crm
modules:
  ext_twilio_configuration:
    name: Twilio Configuration
    fields:
      - name: ProductionSID
        label: Production Account SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

      - name: TestingSID
        label: Testing Account SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

      - name: ProductionToken
        label: Production Auth Token
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

      - name: TestingToken
        label: Testing Auth Token
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

  ext_twilio_script_scene:
    name: Twilio Script Scene
    fields:
      - name: Type
        label: Type
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Select
        options:
          options:
            - Question
            - Dialogue
            - Comment

      - name: Text
        label: Text
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      - name: Script
        label: Script
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: Record
        optios:
          module: ext_twilio_script
          labelField: Scene
          queryFields:
            - Scene

      - name: Order
        label: Order
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Number

  ext_twilio_script:
    name: Twilio Script
    fields:
      - name: CallCenter
        label: Call Center
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: ext_twilio_call_center
          labelField: Name
          queryFields:
            - Name

      - name: Scene
        label: Scene
        isRequired: true
        isPrivate: false
        isMulti: true
        kind: Record
        options:
          module: ext_twilio_script_scene
          labelField: Text
          queryFields:
            - Type
            - Text

  ext_twilio_interaction_answer:
    name: Twilio Interaction Answer
    handle: ext_twilio_interaction_answer
    fields:
      Scene:
        name: Scene
        label: Scene
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: ext_twilio_script_scene
          labelField: Text
          queryFields:
            - Text

      Answer:
        name: Answer
        label: Answer
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

  ext_twilio_interaction:
    name: Twilio Interaction
    fields:
      - name: Answer
        label: Answer
        isRequired: true
        isPrivate: false
        isMulti: true
        kind: Record
        options:
          module: ext_twilio_interaction_answer
          labelField: Scene
          queryFields:
            - Scene
            - Answer

  ext_twilio_call:
    name: Twilio Call
    fields:
      - name: Interaction
        label: Interaction
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: ext_twilio_interaction
          labelField: Answer
          queryFields:
            - Answer

      - name: Recording
        label: Recording
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Url

      - name: Duration
        label: Duration
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: String

      - name: DurationRaw
        label: Duration Raw
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: Number

      - name: CallType
        label: Call Type
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Select
        options:
          options:
            - Inbound
            - Outbound
            - Inbound Missed
            - Outbound Missed

      - name: Contact
        label: Contact
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: contact

      - name: Lead
        label: Lead
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: lead

      - name: PhoneNumber
        label: Phone Number
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      - name: CallSid
        label: Call SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

      - name: CallCenter
        label: Call Center
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: ext_twilio_call_center
          labelField: Name
          queryFields:
            - Name

  ext_twilio_call_center:
    name: Twilio Call Center
    fields:
      - name: Name
        label: Name
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      - name: Client
        label: Client
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: account
          labelField: Name
          queryFields:
            - Name

      - name: Active
        label: Active
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Bool

      - name: Internal
        label: Internal
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Bool

      - name: Workspace
        label: Workspace
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: ext_twilio_workspace
          labelField: Name
          queryFields:
            - Name

      - name: CallWebhook
        label: Call Webhook
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: URL

      - name: PhoneNumber
        label: Phone Number
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      - name: PhoneNumberSid
        label: Phone Number SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

  ext_twilio_worker:
    name: Twilio Worker
    fields:
      - name: Name
        label: Name
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      - name: User
        label: User
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: User

      - name: WorkerSid
        label: Worker SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

      - name: Workspace
        label: Workspace
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: ext_twilio_workspace
          labelField: WorkspaceName
          queryFields:
            - Name
            - WorkspaceName
            - WorkspaceSid

  ext_twilio_workspace:
    name: Twilio Workspace
    fields:
      - name: Name
        label: Name
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      - name: AssignmentCallbackUrl
        label: Assignment Callback Url
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      - name: TaskTimeout
        label: Task Timeout
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Number

      - name: WorkersCount
        label: Total Workers
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Number

      - name: WorkspaceSid
        label: Workspace SID
        isRequired: false
        isPrivate: true
        isMulti: false
        kind: String

      - name: TaskQueueSid
        label: Task Queue SID
        isRequired: false
        isPrivate: true
        isMulti: false
        kind: String

      - name: WorkflowSid
        label: Workflow SID
        isRequired: false
        isPrivate: true
        isMulti: false
        kind: String
