# This file defines the data model required by the Twilio extension.
namespace: crm
modules:
  tw_script_scene:
    name: Twilio Script Scene
    handle: tw_script_scene
    fields:
      Type:
        name: Type
        label: Type
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Select
        options:
          options:
            - Question
            - Dialogue
            - Comment
      Text:
        name: Text
        label: Text
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

  tw_script:
    name: Twilio Script
    handle: tw_script
    fields:
      CallCenter:
        name: CallCenter
        label: Call Center
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: tw_call_center
          labelField: Name
          queryFields:
            - Name

      Scene:
        name: Scene
        label: Scene
        isRequired: true
        isPrivate: false
        isMulti: true
        kind: Record
        options:
          module: tw_script_scene
          labelField: Text
          queryFields:
            - Type
            - Text

  tw_interaction_answer:
    name: Twilio Interaction Answer
    handle: tw_interaction_answer
    fields:
      Scene:
        name: Scene
        label: Scene
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: tw_script_scene
          labelField: Text
          queryFields:
            - Text

      Answer:
        name: Answer
        label: Answer
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

  tw_interaction:
    name: Twilio Interaction
    handle: tw_interaction
    fields:
      Answer:
        name: Answer
        label: Answer
        isRequired: true
        isPrivate: false
        isMulti: true
        kind: Record
        options:
          module: tw_interaction_answer
          labelField: Scene
          queryFields:
            - Scene
            - Answer

  tw_call:
    name: Twilio Call
    handle: tw_call
    fields:
      Interaction:
        name: Interaction
        label: Interaction
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: tw_interaction
          labelField: Answer
          queryFields:
            - Answer

      Recording:
        name: Recording
        label: Recording
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Url

      Duration:
        name: Duration
        label: Duration
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: String

      DurationRaw:
        name: DurationRaw
        label: Duration Raw
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: Number

      CallType:
        name: CallType
        label: Call Type
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Select
        options:
          options:
            - Inbound
            - Outbound
            - Inbound Missed
            - Outbound Missed

      Contact:
        name: Contact
        label: Contact
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: contact

      Lead:
        name: Lead
        label: Lead
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: lead

      PhoneNumber:
        name: PhoneNumber
        label: Phone Number
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      CallSid:
        name: CallSid
        label: Call SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

      CallCenter:
        name: CallCenter
        label: Call Center
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: tw_call_center
          labelField: Name
          queryFields:
            - Name

  tw_call_center:
    name: Twilio Call Center
    handle: tw_call_center
    fields:
      Name:
        name: Name
        label: Name
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      Client:
        name: Client
        label: Client
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: account
          labelField: Name
          queryFields:
            - Name

      Active:
        name: Active
        label: Active
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Bool

      Internal:
        name: Internal
        label: Internal
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Bool

      Workspace:
        name: Workspace
        label: Workspace
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: tw_workspace
          labelField: Name
          queryFields:
            - Name

      PhoneNumber:
        name: PhoneNumber
        label: Phone Number
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      PhoneNumberSid:
        name: PhoneNumberSid
        label: Phone Number SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

  tw_worker:
    name: Twilio Worker
    handle: tw_worker
    fields:
      Name:
        name: Name
        label: Name
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      User:
        name: User
        label: User
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: User

      WorkerSid:
        name: WorkerSid
        label: Worker SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

      Workspace:
        name: Workspace
        label: Workspace
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: Record
        options:
          module: tw_workspace
          labelField: WorkspaceName
          queryFields:
            - Name
            - WorkspaceName
            - WorkspaceDescription
            - WorkspaceSid

  tw_workspace:
    name: Twilio Workspace
    handle: tw_workspace
    fields:
      Name:
        name: Name
        label: Name
        isRequired: true
        isPrivate: false
        isMulti: false
        kind: String

      WorkersCount:
        name: WorkersCount
        label: Total Workers
        isRequired: false
        isPrivate: false
        isMulti: false
        kind: Number

      WorkspaceSid:
        name: WorkspaceSid
        label: Workspace SID
        isRequired: true
        isPrivate: true
        isMulti: false
        kind: String

      CallCenter:
        name: CallCenter
        label: Call Center
        isRequired: false
        isPrivate: false
        isMulti: true
        kind: Record
        options:
          module: tw_call_center

      Worker:
        name: Worker
        label: Worker
        isRequired: false
        isPrivate: false
        isMulti: true
        kind: Record
        options:
          module: tw_worker
          labelField: WorkerName
          queryFields:
            - Name
            - WorkerName
